name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Redeploy to EC2 # Cleaner job name
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
          host: ${{ secrets.PUBLICIP }}
          user: ec2-user
          key: ${{ secrets.LABSUSERPEM }}
          script: |
            cd /home/ec2-user/Aiden-Sean-Kris
            ./redeploy.sh
