name: Deploy to EC2

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
          host: ${{ secrets.PUBLICIP }}
          user: ec2-user
          key: ${{ secrets.LABSUSERPEM }}
          script: |
            cd /Aiden-Sean-Kris
            ./redeploy.sh
