name: Deploy Docker on AWS

on: 
  workflow_dispatch: 

jobs:
  deploy:
    name: Redeploy Docker on EC2
    runs-on: ubuntu-latest
    steps:
      - name: ssh-pipeline
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
          host: ${{ secrets.PUBLICIP }}
          user: ec2-user
          key: ${{ secrets.LABSUSERPEM }}
          script: |
            cd /home/ec2-user/Aiden-Sean-Kris/ec2Docker
            git config --global --add safe.directory /home/ec2-user/Aiden-Sean-Kris
            sudo chmod +x redeploy.sh 
            sudo ./redeploy.sh
