name: Java Maven CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: blackjack
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Wait for MySQL to be ready
      run: sleep 20

    - name: Add .env file
      run: echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env

    - name: Run Maven package
      run: mvn clean package